version: '3.8'

services:
  web:
    image: ${DOCKER_USERNAME}/devops-demo:latest
    container_name: devops-demo
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge 